/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface QuizAttempt {
  'id' : bigint,
  'total' : bigint,
  'user' : Principal,
  'time_taken_seconds' : bigint,
  'correct_by_difficulty' : Array<[string, bigint, bigint]>,
  'score' : bigint,
  'completed_at' : bigint,
  'quiz_id' : string,
  'percentage' : number,
}
export interface QuizAttemptInput {
  'total' : bigint,
  'time_taken_seconds' : bigint,
  'correct_by_difficulty' : Array<[string, bigint, bigint]>,
  'score' : bigint,
  'quiz_id' : string,
  'percentage' : number,
}
export interface _SERVICE {
  'getLeaderboard' : ActorMethod<[string, bigint], Array<QuizAttempt>>,
  'getMyAttempts' : ActorMethod<[], Array<QuizAttempt>>,
  'saveQuizAttempt' : ActorMethod<[QuizAttemptInput], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];