/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuizAttempt = IDL.Record({
  'id' : IDL.Nat,
  'total' : IDL.Nat,
  'user' : IDL.Principal,
  'time_taken_seconds' : IDL.Nat,
  'correct_by_difficulty' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat)),
  'score' : IDL.Nat,
  'completed_at' : IDL.Int,
  'quiz_id' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const QuizAttemptInput = IDL.Record({
  'total' : IDL.Nat,
  'time_taken_seconds' : IDL.Nat,
  'correct_by_difficulty' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat)),
  'score' : IDL.Nat,
  'quiz_id' : IDL.Text,
  'percentage' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getLeaderboard' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(QuizAttempt)],
      ['query'],
    ),
  'getMyAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
  'saveQuizAttempt' : IDL.Func([QuizAttemptInput], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuizAttempt = IDL.Record({
    'id' : IDL.Nat,
    'total' : IDL.Nat,
    'user' : IDL.Principal,
    'time_taken_seconds' : IDL.Nat,
    'correct_by_difficulty' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat)),
    'score' : IDL.Nat,
    'completed_at' : IDL.Int,
    'quiz_id' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const QuizAttemptInput = IDL.Record({
    'total' : IDL.Nat,
    'time_taken_seconds' : IDL.Nat,
    'correct_by_difficulty' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat)),
    'score' : IDL.Nat,
    'quiz_id' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  
  return IDL.Service({
    'getLeaderboard' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(QuizAttempt)],
        ['query'],
      ),
    'getMyAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
    'saveQuizAttempt' : IDL.Func([QuizAttemptInput], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };